// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: tendermint/dalc/dalc.proto

package dalc

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	metro "github.com/tendermint/tendermint/proto/tendermint/metro"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type StatusCode int32

const (
	StatusCode_STATUS_CODE_UNSPECIFIED StatusCode = 0
	StatusCode_STATUS_CODE_SUCCESS     StatusCode = 1
	StatusCode_STATUS_CODE_TIMEOUT     StatusCode = 2
	StatusCode_STATUS_CODE_ERROR       StatusCode = 3
)

var StatusCode_name = map[int32]string{
	0: "STATUS_CODE_UNSPECIFIED",
	1: "STATUS_CODE_SUCCESS",
	2: "STATUS_CODE_TIMEOUT",
	3: "STATUS_CODE_ERROR",
}

var StatusCode_value = map[string]int32{
	"STATUS_CODE_UNSPECIFIED": 0,
	"STATUS_CODE_SUCCESS":     1,
	"STATUS_CODE_TIMEOUT":     2,
	"STATUS_CODE_ERROR":       3,
}

func (x StatusCode) String() string {
	return proto.EnumName(StatusCode_name, int32(x))
}

func (StatusCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8355feb29c44de61, []int{0}
}

type DAResponse struct {
	Code     StatusCode `protobuf:"varint,1,opt,name=code,proto3,enum=dalc.StatusCode" json:"code,omitempty"`
	Message  string     `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	DAHeight int64      `protobuf:"varint,3,opt,name=da_height,json=daHeight,proto3" json:"da_height,omitempty"`
}

func (m *DAResponse) Reset()         { *m = DAResponse{} }
func (m *DAResponse) String() string { return proto.CompactTextString(m) }
func (*DAResponse) ProtoMessage()    {}
func (*DAResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8355feb29c44de61, []int{0}
}
func (m *DAResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DAResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DAResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DAResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DAResponse.Merge(m, src)
}
func (m *DAResponse) XXX_Size() int {
	return m.Size()
}
func (m *DAResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DAResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DAResponse proto.InternalMessageInfo

func (m *DAResponse) GetCode() StatusCode {
	if m != nil {
		return m.Code
	}
	return StatusCode_STATUS_CODE_UNSPECIFIED
}

func (m *DAResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *DAResponse) GetDAHeight() int64 {
	if m != nil {
		return m.DAHeight
	}
	return 0
}

type SubmitBlockRequest struct {
	Block *metro.MultiBlock `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
}

func (m *SubmitBlockRequest) Reset()         { *m = SubmitBlockRequest{} }
func (m *SubmitBlockRequest) String() string { return proto.CompactTextString(m) }
func (*SubmitBlockRequest) ProtoMessage()    {}
func (*SubmitBlockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8355feb29c44de61, []int{1}
}
func (m *SubmitBlockRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SubmitBlockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SubmitBlockRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SubmitBlockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitBlockRequest.Merge(m, src)
}
func (m *SubmitBlockRequest) XXX_Size() int {
	return m.Size()
}
func (m *SubmitBlockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitBlockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitBlockRequest proto.InternalMessageInfo

func (m *SubmitBlockRequest) GetBlock() *metro.MultiBlock {
	if m != nil {
		return m.Block
	}
	return nil
}

type SubmitBlockResponse struct {
	Result *DAResponse `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (m *SubmitBlockResponse) Reset()         { *m = SubmitBlockResponse{} }
func (m *SubmitBlockResponse) String() string { return proto.CompactTextString(m) }
func (*SubmitBlockResponse) ProtoMessage()    {}
func (*SubmitBlockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8355feb29c44de61, []int{2}
}
func (m *SubmitBlockResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SubmitBlockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SubmitBlockResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SubmitBlockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitBlockResponse.Merge(m, src)
}
func (m *SubmitBlockResponse) XXX_Size() int {
	return m.Size()
}
func (m *SubmitBlockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitBlockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitBlockResponse proto.InternalMessageInfo

func (m *SubmitBlockResponse) GetResult() *DAResponse {
	if m != nil {
		return m.Result
	}
	return nil
}

type CheckBlockAvailabilityRequest struct {
	DAHeight int64 `protobuf:"varint,1,opt,name=da_height,json=daHeight,proto3" json:"da_height,omitempty"`
}

func (m *CheckBlockAvailabilityRequest) Reset()         { *m = CheckBlockAvailabilityRequest{} }
func (m *CheckBlockAvailabilityRequest) String() string { return proto.CompactTextString(m) }
func (*CheckBlockAvailabilityRequest) ProtoMessage()    {}
func (*CheckBlockAvailabilityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8355feb29c44de61, []int{3}
}
func (m *CheckBlockAvailabilityRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CheckBlockAvailabilityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CheckBlockAvailabilityRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CheckBlockAvailabilityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckBlockAvailabilityRequest.Merge(m, src)
}
func (m *CheckBlockAvailabilityRequest) XXX_Size() int {
	return m.Size()
}
func (m *CheckBlockAvailabilityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckBlockAvailabilityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckBlockAvailabilityRequest proto.InternalMessageInfo

func (m *CheckBlockAvailabilityRequest) GetDAHeight() int64 {
	if m != nil {
		return m.DAHeight
	}
	return 0
}

type CheckBlockAvailabilityResponse struct {
	Result        *DAResponse `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	DataAvailable bool        `protobuf:"varint,2,opt,name=data_available,json=dataAvailable,proto3" json:"data_available,omitempty"`
}

func (m *CheckBlockAvailabilityResponse) Reset()         { *m = CheckBlockAvailabilityResponse{} }
func (m *CheckBlockAvailabilityResponse) String() string { return proto.CompactTextString(m) }
func (*CheckBlockAvailabilityResponse) ProtoMessage()    {}
func (*CheckBlockAvailabilityResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8355feb29c44de61, []int{4}
}
func (m *CheckBlockAvailabilityResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CheckBlockAvailabilityResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CheckBlockAvailabilityResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CheckBlockAvailabilityResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckBlockAvailabilityResponse.Merge(m, src)
}
func (m *CheckBlockAvailabilityResponse) XXX_Size() int {
	return m.Size()
}
func (m *CheckBlockAvailabilityResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckBlockAvailabilityResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckBlockAvailabilityResponse proto.InternalMessageInfo

func (m *CheckBlockAvailabilityResponse) GetResult() *DAResponse {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *CheckBlockAvailabilityResponse) GetDataAvailable() bool {
	if m != nil {
		return m.DataAvailable
	}
	return false
}

type RetrieveBlocksRequest struct {
	DAHeight int64 `protobuf:"varint,1,opt,name=da_height,json=daHeight,proto3" json:"da_height,omitempty"`
}

func (m *RetrieveBlocksRequest) Reset()         { *m = RetrieveBlocksRequest{} }
func (m *RetrieveBlocksRequest) String() string { return proto.CompactTextString(m) }
func (*RetrieveBlocksRequest) ProtoMessage()    {}
func (*RetrieveBlocksRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8355feb29c44de61, []int{5}
}
func (m *RetrieveBlocksRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RetrieveBlocksRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RetrieveBlocksRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RetrieveBlocksRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrieveBlocksRequest.Merge(m, src)
}
func (m *RetrieveBlocksRequest) XXX_Size() int {
	return m.Size()
}
func (m *RetrieveBlocksRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrieveBlocksRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RetrieveBlocksRequest proto.InternalMessageInfo

func (m *RetrieveBlocksRequest) GetDAHeight() int64 {
	if m != nil {
		return m.DAHeight
	}
	return 0
}

type RetrieveBlocksResponse struct {
	Result *DAResponse         `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Blocks []*metro.MultiBlock `protobuf:"bytes,2,rep,name=blocks,proto3" json:"blocks,omitempty"`
}

func (m *RetrieveBlocksResponse) Reset()         { *m = RetrieveBlocksResponse{} }
func (m *RetrieveBlocksResponse) String() string { return proto.CompactTextString(m) }
func (*RetrieveBlocksResponse) ProtoMessage()    {}
func (*RetrieveBlocksResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8355feb29c44de61, []int{6}
}
func (m *RetrieveBlocksResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RetrieveBlocksResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RetrieveBlocksResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RetrieveBlocksResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrieveBlocksResponse.Merge(m, src)
}
func (m *RetrieveBlocksResponse) XXX_Size() int {
	return m.Size()
}
func (m *RetrieveBlocksResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrieveBlocksResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RetrieveBlocksResponse proto.InternalMessageInfo

func (m *RetrieveBlocksResponse) GetResult() *DAResponse {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *RetrieveBlocksResponse) GetBlocks() []*metro.MultiBlock {
	if m != nil {
		return m.Blocks
	}
	return nil
}

func init() {
	proto.RegisterEnum("dalc.StatusCode", StatusCode_name, StatusCode_value)
	proto.RegisterType((*DAResponse)(nil), "dalc.DAResponse")
	proto.RegisterType((*SubmitBlockRequest)(nil), "dalc.SubmitBlockRequest")
	proto.RegisterType((*SubmitBlockResponse)(nil), "dalc.SubmitBlockResponse")
	proto.RegisterType((*CheckBlockAvailabilityRequest)(nil), "dalc.CheckBlockAvailabilityRequest")
	proto.RegisterType((*CheckBlockAvailabilityResponse)(nil), "dalc.CheckBlockAvailabilityResponse")
	proto.RegisterType((*RetrieveBlocksRequest)(nil), "dalc.RetrieveBlocksRequest")
	proto.RegisterType((*RetrieveBlocksResponse)(nil), "dalc.RetrieveBlocksResponse")
}

func init() { proto.RegisterFile("tendermint/dalc/dalc.proto", fileDescriptor_8355feb29c44de61) }

var fileDescriptor_8355feb29c44de61 = []byte{
	// 547 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x41, 0x8f, 0xd2, 0x40,
	0x14, 0xa6, 0xb0, 0xae, 0xec, 0x43, 0x09, 0xce, 0xba, 0xbb, 0xb5, 0xbb, 0x56, 0xac, 0x6b, 0x82,
	0x1e, 0x4a, 0x82, 0xc6, 0xab, 0x29, 0x6d, 0xcd, 0x62, 0x44, 0x36, 0x53, 0xb8, 0x78, 0x21, 0xa5,
	0x9d, 0x40, 0xb3, 0x2d, 0xdd, 0x6d, 0xa7, 0xa8, 0x3f, 0xc1, 0x9b, 0x3f, 0xcb, 0xe3, 0x1e, 0x3d,
	0x19, 0x03, 0x7f, 0xc4, 0x30, 0x53, 0xa4, 0x20, 0x62, 0xd6, 0x4b, 0xf3, 0xfa, 0xbe, 0xf7, 0xde,
	0x7c, 0xdf, 0xbc, 0x2f, 0x03, 0x12, 0x25, 0x63, 0x97, 0x44, 0x81, 0x37, 0xa6, 0x75, 0xd7, 0xf6,
	0x1d, 0xf6, 0x51, 0x2f, 0xa3, 0x90, 0x86, 0x68, 0x67, 0x1e, 0x4b, 0x8f, 0x33, 0x15, 0x01, 0xa1,
	0x51, 0x58, 0x0f, 0x12, 0x9f, 0x7a, 0x03, 0x3f, 0x74, 0x2e, 0x78, 0xa1, 0x74, 0x7f, 0x18, 0x0e,
	0x43, 0x16, 0xd6, 0xe7, 0x11, 0xcf, 0x2a, 0x1f, 0x01, 0x0c, 0x0d, 0x93, 0xf8, 0x32, 0x1c, 0xc7,
	0x04, 0x9d, 0xc2, 0x8e, 0x13, 0xba, 0x44, 0x14, 0xaa, 0x42, 0xad, 0xdc, 0xa8, 0xa8, 0xec, 0x1c,
	0x8b, 0xda, 0x34, 0x89, 0xf5, 0xd0, 0x25, 0x98, 0xa1, 0x48, 0x84, 0xdb, 0x01, 0x89, 0x63, 0x7b,
	0x48, 0xc4, 0x7c, 0x55, 0xa8, 0xed, 0xe1, 0xc5, 0x2f, 0x7a, 0x06, 0x7b, 0xae, 0xdd, 0x1f, 0x11,
	0x6f, 0x38, 0xa2, 0x62, 0xa1, 0x2a, 0xd4, 0x0a, 0xcd, 0x3b, 0xd3, 0x1f, 0x8f, 0x8a, 0x86, 0x76,
	0xc6, 0x72, 0xb8, 0xe8, 0xda, 0x3c, 0x52, 0xce, 0x00, 0x59, 0xc9, 0x20, 0xf0, 0x68, 0x73, 0xce,
	0x11, 0x93, 0xab, 0x84, 0xc4, 0x14, 0x35, 0xe0, 0x16, 0xe3, 0xcc, 0x18, 0x94, 0x1a, 0x27, 0xea,
	0x52, 0x97, 0xca, 0x74, 0xa9, 0xed, 0xb9, 0x2e, 0xde, 0xc3, 0x4b, 0x95, 0xd7, 0xb0, 0xbf, 0x32,
	0x29, 0xd5, 0x52, 0x83, 0xdd, 0x88, 0xc4, 0x89, 0x4f, 0xd3, 0x59, 0xa9, 0x9a, 0xa5, 0x5a, 0x9c,
	0xe2, 0xca, 0x5b, 0x78, 0xa8, 0x8f, 0x88, 0x73, 0xc1, 0xfa, 0xb5, 0x89, 0xed, 0xf9, 0xf6, 0xc0,
	0xf3, 0x3d, 0xfa, 0x79, 0xc1, 0x6a, 0x45, 0x96, 0xb0, 0x55, 0xd6, 0x15, 0xc8, 0x7f, 0x9b, 0x75,
	0x53, 0x5e, 0xe8, 0x29, 0x94, 0x5d, 0x9b, 0xda, 0x7d, 0x9b, 0x8f, 0xf1, 0xf9, 0x75, 0x17, 0xf1,
	0xdd, 0x79, 0x56, 0x5b, 0x24, 0x95, 0x26, 0x1c, 0x60, 0x42, 0x23, 0x8f, 0x4c, 0x08, 0x3b, 0x35,
	0xfe, 0x0f, 0xda, 0x9f, 0xe0, 0x70, 0x7d, 0xc6, 0x8d, 0xe9, 0xbe, 0x84, 0x5d, 0xb6, 0x90, 0x58,
	0xcc, 0x57, 0x0b, 0xff, 0x5c, 0x5e, 0x5a, 0xfb, 0x3c, 0x02, 0x58, 0x1a, 0x0c, 0x1d, 0xc3, 0x91,
	0xd5, 0xd5, 0xba, 0x3d, 0xab, 0xaf, 0x77, 0x0c, 0xb3, 0xdf, 0x7b, 0x6f, 0x9d, 0x9b, 0x7a, 0xeb,
	0x4d, 0xcb, 0x34, 0x2a, 0x39, 0x74, 0x04, 0xfb, 0x59, 0xd0, 0xea, 0xe9, 0xba, 0x69, 0x59, 0x15,
	0x61, 0x1d, 0xe8, 0xb6, 0xda, 0x66, 0xa7, 0xd7, 0xad, 0xe4, 0xd1, 0x01, 0xdc, 0xcb, 0x02, 0x26,
	0xc6, 0x1d, 0x5c, 0x29, 0x34, 0xbe, 0xe4, 0xa1, 0x64, 0x68, 0xef, 0x74, 0x8b, 0x44, 0x13, 0xcf,
	0x21, 0xc8, 0x80, 0x52, 0xc6, 0x41, 0x48, 0x4c, 0x7d, 0xff, 0x87, 0x3d, 0xa5, 0x07, 0x1b, 0x10,
	0x7e, 0x0b, 0x4a, 0x0e, 0x11, 0x38, 0xdc, 0xbc, 0x7a, 0xf4, 0x84, 0xb7, 0x6d, 0x35, 0x99, 0x74,
	0xba, 0xbd, 0xe8, 0xf7, 0x31, 0x6d, 0x28, 0xaf, 0xae, 0x0a, 0x1d, 0xf3, 0xce, 0x8d, 0x26, 0x90,
	0x4e, 0x36, 0x83, 0x8b, 0x71, 0xcd, 0xf3, 0x6f, 0x53, 0x59, 0xb8, 0x9e, 0xca, 0xc2, 0xcf, 0xa9,
	0x2c, 0x7c, 0x9d, 0xc9, 0xb9, 0xeb, 0x99, 0x9c, 0xfb, 0x3e, 0x93, 0x73, 0x1f, 0x5e, 0x0d, 0x3d,
	0x3a, 0x4a, 0x06, 0xaa, 0x13, 0x06, 0xf5, 0xcc, 0xf3, 0x92, 0x09, 0xf9, 0x6b, 0xb2, 0xf6, 0x38,
	0x0d, 0x76, 0x59, 0xfa, 0xc5, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xde, 0x2b, 0xa6, 0x0b, 0xb6,
	0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DALCServiceClient is the client API for DALCService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DALCServiceClient interface {
	SubmitBlock(ctx context.Context, in *SubmitBlockRequest, opts ...grpc.CallOption) (*SubmitBlockResponse, error)
	CheckBlockAvailability(ctx context.Context, in *CheckBlockAvailabilityRequest, opts ...grpc.CallOption) (*CheckBlockAvailabilityResponse, error)
	RetrieveBlocks(ctx context.Context, in *RetrieveBlocksRequest, opts ...grpc.CallOption) (*RetrieveBlocksResponse, error)
}

type dALCServiceClient struct {
	cc *grpc.ClientConn
}

func NewDALCServiceClient(cc *grpc.ClientConn) DALCServiceClient {
	return &dALCServiceClient{cc}
}

func (c *dALCServiceClient) SubmitBlock(ctx context.Context, in *SubmitBlockRequest, opts ...grpc.CallOption) (*SubmitBlockResponse, error) {
	out := new(SubmitBlockResponse)
	err := c.cc.Invoke(ctx, "/dalc.DALCService/SubmitBlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dALCServiceClient) CheckBlockAvailability(ctx context.Context, in *CheckBlockAvailabilityRequest, opts ...grpc.CallOption) (*CheckBlockAvailabilityResponse, error) {
	out := new(CheckBlockAvailabilityResponse)
	err := c.cc.Invoke(ctx, "/dalc.DALCService/CheckBlockAvailability", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dALCServiceClient) RetrieveBlocks(ctx context.Context, in *RetrieveBlocksRequest, opts ...grpc.CallOption) (*RetrieveBlocksResponse, error) {
	out := new(RetrieveBlocksResponse)
	err := c.cc.Invoke(ctx, "/dalc.DALCService/RetrieveBlocks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DALCServiceServer is the server API for DALCService service.
type DALCServiceServer interface {
	SubmitBlock(context.Context, *SubmitBlockRequest) (*SubmitBlockResponse, error)
	CheckBlockAvailability(context.Context, *CheckBlockAvailabilityRequest) (*CheckBlockAvailabilityResponse, error)
	RetrieveBlocks(context.Context, *RetrieveBlocksRequest) (*RetrieveBlocksResponse, error)
}

// UnimplementedDALCServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDALCServiceServer struct {
}

func (*UnimplementedDALCServiceServer) SubmitBlock(ctx context.Context, req *SubmitBlockRequest) (*SubmitBlockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitBlock not implemented")
}
func (*UnimplementedDALCServiceServer) CheckBlockAvailability(ctx context.Context, req *CheckBlockAvailabilityRequest) (*CheckBlockAvailabilityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckBlockAvailability not implemented")
}
func (*UnimplementedDALCServiceServer) RetrieveBlocks(ctx context.Context, req *RetrieveBlocksRequest) (*RetrieveBlocksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetrieveBlocks not implemented")
}

func RegisterDALCServiceServer(s *grpc.Server, srv DALCServiceServer) {
	s.RegisterService(&_DALCService_serviceDesc, srv)
}

func _DALCService_SubmitBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DALCServiceServer).SubmitBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dalc.DALCService/SubmitBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DALCServiceServer).SubmitBlock(ctx, req.(*SubmitBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DALCService_CheckBlockAvailability_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckBlockAvailabilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DALCServiceServer).CheckBlockAvailability(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dalc.DALCService/CheckBlockAvailability",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DALCServiceServer).CheckBlockAvailability(ctx, req.(*CheckBlockAvailabilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DALCService_RetrieveBlocks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveBlocksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DALCServiceServer).RetrieveBlocks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dalc.DALCService/RetrieveBlocks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DALCServiceServer).RetrieveBlocks(ctx, req.(*RetrieveBlocksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DALCService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dalc.DALCService",
	HandlerType: (*DALCServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitBlock",
			Handler:    _DALCService_SubmitBlock_Handler,
		},
		{
			MethodName: "CheckBlockAvailability",
			Handler:    _DALCService_CheckBlockAvailability_Handler,
		},
		{
			MethodName: "RetrieveBlocks",
			Handler:    _DALCService_RetrieveBlocks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tendermint/dalc/dalc.proto",
}

func (m *DAResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DAResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DAResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.DAHeight != 0 {
		i = encodeVarintDalc(dAtA, i, uint64(m.DAHeight))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Message) > 0 {
		i -= len(m.Message)
		copy(dAtA[i:], m.Message)
		i = encodeVarintDalc(dAtA, i, uint64(len(m.Message)))
		i--
		dAtA[i] = 0x12
	}
	if m.Code != 0 {
		i = encodeVarintDalc(dAtA, i, uint64(m.Code))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *SubmitBlockRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SubmitBlockRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SubmitBlockRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Block != nil {
		{
			size, err := m.Block.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintDalc(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *SubmitBlockResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SubmitBlockResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SubmitBlockResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Result != nil {
		{
			size, err := m.Result.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintDalc(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *CheckBlockAvailabilityRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CheckBlockAvailabilityRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CheckBlockAvailabilityRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.DAHeight != 0 {
		i = encodeVarintDalc(dAtA, i, uint64(m.DAHeight))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *CheckBlockAvailabilityResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CheckBlockAvailabilityResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CheckBlockAvailabilityResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.DataAvailable {
		i--
		if m.DataAvailable {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if m.Result != nil {
		{
			size, err := m.Result.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintDalc(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *RetrieveBlocksRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RetrieveBlocksRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RetrieveBlocksRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.DAHeight != 0 {
		i = encodeVarintDalc(dAtA, i, uint64(m.DAHeight))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *RetrieveBlocksResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RetrieveBlocksResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RetrieveBlocksResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Blocks) > 0 {
		for iNdEx := len(m.Blocks) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Blocks[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintDalc(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if m.Result != nil {
		{
			size, err := m.Result.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintDalc(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintDalc(dAtA []byte, offset int, v uint64) int {
	offset -= sovDalc(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *DAResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Code != 0 {
		n += 1 + sovDalc(uint64(m.Code))
	}
	l = len(m.Message)
	if l > 0 {
		n += 1 + l + sovDalc(uint64(l))
	}
	if m.DAHeight != 0 {
		n += 1 + sovDalc(uint64(m.DAHeight))
	}
	return n
}

func (m *SubmitBlockRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Block != nil {
		l = m.Block.Size()
		n += 1 + l + sovDalc(uint64(l))
	}
	return n
}

func (m *SubmitBlockResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Result != nil {
		l = m.Result.Size()
		n += 1 + l + sovDalc(uint64(l))
	}
	return n
}

func (m *CheckBlockAvailabilityRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.DAHeight != 0 {
		n += 1 + sovDalc(uint64(m.DAHeight))
	}
	return n
}

func (m *CheckBlockAvailabilityResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Result != nil {
		l = m.Result.Size()
		n += 1 + l + sovDalc(uint64(l))
	}
	if m.DataAvailable {
		n += 2
	}
	return n
}

func (m *RetrieveBlocksRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.DAHeight != 0 {
		n += 1 + sovDalc(uint64(m.DAHeight))
	}
	return n
}

func (m *RetrieveBlocksResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Result != nil {
		l = m.Result.Size()
		n += 1 + l + sovDalc(uint64(l))
	}
	if len(m.Blocks) > 0 {
		for _, e := range m.Blocks {
			l = e.Size()
			n += 1 + l + sovDalc(uint64(l))
		}
	}
	return n
}

func sovDalc(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozDalc(x uint64) (n int) {
	return sovDalc(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *DAResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDalc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DAResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DAResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Code", wireType)
			}
			m.Code = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDalc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Code |= StatusCode(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Message", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDalc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDalc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDalc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Message = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DAHeight", wireType)
			}
			m.DAHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDalc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DAHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipDalc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDalc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SubmitBlockRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDalc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SubmitBlockRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SubmitBlockRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Block", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDalc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDalc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDalc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Block == nil {
				m.Block = &metro.MultiBlock{}
			}
			if err := m.Block.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDalc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDalc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SubmitBlockResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDalc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SubmitBlockResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SubmitBlockResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Result", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDalc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDalc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDalc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Result == nil {
				m.Result = &DAResponse{}
			}
			if err := m.Result.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDalc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDalc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CheckBlockAvailabilityRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDalc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CheckBlockAvailabilityRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CheckBlockAvailabilityRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DAHeight", wireType)
			}
			m.DAHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDalc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DAHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipDalc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDalc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CheckBlockAvailabilityResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDalc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CheckBlockAvailabilityResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CheckBlockAvailabilityResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Result", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDalc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDalc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDalc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Result == nil {
				m.Result = &DAResponse{}
			}
			if err := m.Result.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DataAvailable", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDalc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.DataAvailable = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipDalc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDalc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RetrieveBlocksRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDalc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RetrieveBlocksRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RetrieveBlocksRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DAHeight", wireType)
			}
			m.DAHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDalc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DAHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipDalc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDalc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RetrieveBlocksResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDalc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RetrieveBlocksResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RetrieveBlocksResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Result", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDalc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDalc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDalc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Result == nil {
				m.Result = &DAResponse{}
			}
			if err := m.Result.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Blocks", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDalc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDalc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDalc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Blocks = append(m.Blocks, &metro.MultiBlock{})
			if err := m.Blocks[len(m.Blocks)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDalc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDalc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipDalc(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowDalc
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDalc
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDalc
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthDalc
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupDalc
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthDalc
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthDalc        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowDalc          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupDalc = fmt.Errorf("proto: unexpected end of group")
)
